version: "3"

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
  postgres:
    image: postgres:14.11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=art-peace-user
      - POSTGRES_DB=art-peace-db
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - 8080:8080
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - ART_PEACE_END_TIME=3000000000
      - ART_PEACE_HOST=0328ced46664355fc4b885ae7011af202313056a7e3d44827fb24c9d3206aaa0
      - ROUND_NUMBER=2
      - CANVAS_FACTORY_CONTRACT_ADDRESS=0x02458a105b42db469fb1f8b35ab3ce126dab5a0881ad3c2bbf36bec0a34168c5
    volumes:
      - nfts:/app/nfts
  consumer:
    build:
      dockerfile: backend/Dockerfile.consumer
      context: .
    ports:
      - 8081:8081
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - ROUND_NUMBER=2
      - CANVAS_FACTORY_CONTRACT_ADDRESS=0x02458a105b42db469fb1f8b35ab3ce126dab5a0881ad3c2bbf36bec0a34168c5
      - AVAIL_TURBO_API_KEY=${AVAIL_TURBO_API_KEY}
      - ENABLE_TURBODA=false
    volumes:
      - nfts:/app/nfts
      - worlds:/app/worlds
  indexer:
    build:
      dockerfile: indexer/Dockerfile.worlds
      context: .
    links:
      - backend
    environment:
      - APIBARA_STREAM_URL=https://mainnet.starknet.a5a.ch
      - AUTH_TOKEN=${APIBARA_AUTH_TOKEN}
      - CONSUMER_TARGET_URL=http://art-peace-consumer-1:8081/consume-indexer-msg
      - PERSIST_TO_REDIS=redis://art-peace-redis-1:6379
      - INDEXER_ID=canvas-worlds-indexer-id
      - CANVAS_FACTORY_CONTRACT_ADDRESS=0x02458a105b42db469fb1f8b35ab3ce126dab5a0881ad3c2bbf36bec0a34168c5
    volumes:
      - configs:/configs
    restart: on-failure
  frontend-next:
    build:
      dockerfile: frontend-next/Dockerfile
      context: .
    ports:
      - 3000:3000
    links:
      - backend
    environment:
      - REACT_APP_BASE_PIXEL_TIMER=30000
      - REACT_APP_ROUND_NUMBER=2
      - NEXT_PUBLIC_CANVAS_CONTRACT_ADDRESS=0x02458a105b42db469fb1f8b35ab3ce126dab5a0881ad3c2bbf36bec0a34168c5
      - NEXT_PUBLIC_BASE_PIXEL_TIMER=5000
      - NEXT_PUBLIC_ROUND_NUMBER=3
      - NEXT_PUBLIC_WEBSOCKET_URL=wss://api.art-peace.net
      - NEXT_PUBLIC_BACKEND_URL=https://api.art-peace.net
      - NEXT_PUBLIC_HAS_LAUNCHED=true
      - NEXT_PUBLIC_BASE_WORLD_ID=13
      - NEXT_PUBLIC_UPLOAD_ENABLED=true
      - NEXT_PUBLIC_CHAIN_ID=SN_MAIN
    volumes:
      - ./frontend-next/package.json:/app/package.json
      - ./frontend-next/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./frontend-next/public/:/app/public
      - ./frontend-next/src:/app/src
      - configs:/app/src/configs

volumes:
  redis:
  postgres:
  nfts:
  worlds:
  configs:
