apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.stencils.claim }}
  labels:
    app: templates
spec:
  storageClassName: {{ .Values.volumes.stencils.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.stencils.storage }}
